spring.application.name: init-container
spring:
  main:
    web-application-type: none
    banner-mode: off
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: ${KEY_VAULT_URI}

logging:
  level:
    root: info
    com.azure.identity: error